{-# OPTIONS --lossy-unification #-}
-- Quotienting a theory by more equations.
--
-- Given a theory `σeq` and a further family `E` of equations over the
-- same signature, `σeq / E` is the theory with that signature and the
-- union of the equations.  The definition is trivial -- it is
-- `_∪Eqns_` from `Theory.Presentation` -- and all the content is in
-- what the construction *is*, which is three things.
--
-- 1. A full subcategory.  Satisfying `E` is a property of a
--    `σeq`-model, not extra structure: `Homo` mentions only the
--    signature, so it does not see the equations at all.  So the
--    property appears as a `PropertyOver` on `MOD σeq`, and
--    `MOD (σeq / E)` is isomorphic -- bijective on objects and fully
--    faithful -- to its total category.  This is the unsorted mirror
--    of the way `EQNSᴰ` layers over `ALGᴰ` in `Theory.Sorted`.
--
-- 2. Half of a factorization system on THEORY.  A map of theories
--    `(F , pF) : (σ , σeq) → (τ , τeq)` splits as
--
--        (σ , σeq) --(F , pushPres)--> (τ , F* σeq)
--                  --(id , pullPres)--> (τ , τeq)
--
--    where `F* σeq = pushEqns F σeq` is τ's signature carrying exactly
--    σeq's equations read through F.  The first map adds operations
--    and imposes nothing new; the second is the identity on the
--    signature, and a map that is the identity on the signature is
--    precisely a quotient map: `quotCatIso` shows `σeq / σeq'` and
--    `σeq'` are isomorphic in THEORY whenever there is a vertical map
--    `σeq → σeq'`, and `addEqnsIsQuot` factors the second map through
--    the literal quotient map of this file.  `orthogonal` supplies the
--    unique diagonal filler, so the two classes are orthogonal.
--    Uniqueness is free -- `PresEqns` is a proposition, so a map of
--    theories is determined by its signature part -- and the content
--    is the construction of the filler's `PresEqns` witness.
--
-- 3. A reflection.  The inclusion `MOD (σeq / E) ↪ MOD σeq` has a left
--    adjoint, and no quotient HIT is needed to build it: the
--    reflection of a model `B` is `B` *presented over the quotient
--    theory by its own multiplication table*, one relation
--    `op(x) = ⟨op⟩⟦x⟧` for every operation and tuple.  Relations are
--    equations with no variables (see `Theory.Presentation`), so the
--    table forces nothing beyond B's own structure, while the base
--    theory `σeq / E` forces `E`; the presented model is therefore B
--    modulo the congruence generated by E.  `UPReflectMOD` is the
--    adjunction isomorphism of hom-sets and `UPReflectNat` its
--    naturality.  This is what makes abelianization an instance.
--
-- Everything is stated for the *unsorted* framework of
-- `Cubical.Algebra.Theory`, because THEORY-as-a-category lives there
-- (`Theory.Theories`) and the factorization is a statement about
-- THEORY.
module Cubical.Algebra.Theory.Constructions.Quotient where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Equiv
open import Cubical.Foundations.Function
open import Cubical.Foundations.HLevels
open import Cubical.Foundations.Isomorphism hiding (isIso)
open import Cubical.Foundations.Structure

open import Cubical.Data.Sigma
open import Cubical.Data.Sum using (_⊎_; inl; inr)
open import Cubical.Data.Unit

open import Cubical.Categories.Category
open import Cubical.Categories.Functor
open import Cubical.Categories.Displayed.Base
open import Cubical.Categories.Displayed.Instances.PropertyOver
open import Cubical.Categories.Instances.Sets
open import Cubical.Categories.Instances.TotalCategory

open import Cubical.Algebra.Theory
open import Cubical.Algebra.Theory.Category
open import Cubical.Algebra.Theory.Theories
open import Cubical.Algebra.Theory.Constructions
open import Cubical.Algebra.Theory.Presentation

private
  variable
    ℓ ℓ' ℓ'' ℓE ℓv ℓX : Level
    ℓ1 ℓ2 : Level

open AlgTheorySig
open AlgTheoryEqns using (eqns; vars; lhs; rhs)
open SigMap
open SetSig
open Presentation
open Category using (ob)
open Functor
open Categoryᴰ using (ob[_])

-- The quotient theory: same signature, more equations.
module _ {σ : AlgTheorySig ℓ ℓ'} where
  _/_ : AlgTheoryEqns σ ℓ'' ℓv → AlgTheoryEqns σ ℓE ℓv
    → AlgTheoryEqns σ (ℓ-max ℓ'' ℓE) ℓv
  _/_ = _∪Eqns_

module _ {σ : AlgTheorySig ℓ ℓ'} (σeq : AlgTheoryEqns σ ℓ'' ℓv)
  (E : AlgTheoryEqns σ ℓE ℓv) where

  -- the quotient map, in THEORY: identity on the signature
  quotPres : PresEqns σeq (σeq / E) ℓX idSigMap
  quotPres X B e ρ = Alg.⟦_⟧eqn B (inl e) ρ

  -- the induced functor on models
  U/ : Functor (MOD (σeq / E) ℓX) (MOD σeq ℓX)
  U/ .F-ob (X , B) = X , reindexModel quotPres X B
  U/ .F-hom (f , ϕ) = f , reindexHomo quotPres ϕ
  U/ .F-id = refl
  U/ .F-seq _ _ = refl

  -- Satisfying the extra equations is a *property* of a model, so it
  -- appears as a `PropertyOver` on `MOD σeq`, exactly as `EQNSᴰ` sits
  -- over `ALG` in the sorted development.
  SATᴰ : (ℓX : Level) → Categoryᴰ (MOD σeq ℓX) _ ℓ-zero
  SATᴰ ℓX =
    PropertyOver (MOD σeq ℓX) (λ M → Sat E (Alg.⟨_⟩⟦_⟧op (M .snd)))

  isPropSATᴰ : (ℓX : Level) (M : ob (MOD σeq ℓX))
    → isProp (ob[ SATᴰ ℓX ] M)
  isPropSATᴰ ℓX M = isPropSat (M .fst .snd)

  -- `Homo` mentions the signature only, so homomorphisms of models of
  -- the quotient theory *are* homomorphisms of the underlying models.
  private
    opHom/ : {X Y : Type ℓX} {f : X → Y}
      {B : Alg (σeq / E) X} {C : Alg (σeq / E) Y}
      → Homo (σeq / E) f B C
      → (op : σ .ops) (x : σ .arities op → X) (y : X)
      → y ≡ Alg.⟨_⟩⟦_⟧op B op x
      → f y ≡ Alg.⟨_⟩⟦_⟧op C op (f ∘ x)
    opHom/ ϕ = Homo.op-hom ϕ

    opHomσ : {X Y : Type ℓX} {f : X → Y}
      {B : Alg σeq X} {C : Alg σeq Y}
      → Homo σeq f B C
      → (op : σ .ops) (x : σ .arities op → X) (y : X)
      → y ≡ Alg.⟨_⟩⟦_⟧op B op x
      → f y ≡ Alg.⟨_⟩⟦_⟧op C op (f ∘ x)
    opHomσ ψ = Homo.op-hom ψ

  homoIso : {X : Type ℓX} {Y : Type ℓX}
    {B : Alg (σeq / E) X} {C : Alg (σeq / E) Y} {f : X → Y}
    → Iso (Homo (σeq / E) f B C)
          (Homo σeq f (Alg∪ σeq E B) (Alg∪ σeq E C))
  homoIso .Iso.fun ϕ .Homo.op-hom = opHom/ ϕ
  homoIso .Iso.inv ψ .Homo.op-hom = opHomσ ψ
  homoIso .Iso.sec _ = refl
  homoIso .Iso.ret _ = refl

  module _ (ℓX : Level) where
    private
      MOD/ = MOD (σeq / E) ℓX
      MODσ = MOD σeq ℓX

    -- objects: a model of `σeq / E` is exactly a model of `σeq`
    -- together with a proof (a proposition) that E holds
    obIso : Iso (ob MOD/) (ob (∫C (SATᴰ ℓX)))
    obIso = compIso
      (Σ-cong-iso-snd (λ X → AlgIso∪ σeq E (X .snd)))
      (invIso Σ-assoc-Iso)

    -- morphisms: `Homo` mentions only the signature, so nothing changes
    homIso : {M N : ob MOD/}
      → Iso (MOD/ [ M , N ]) (MODσ [ U/ .F-ob M , U/ .F-ob N ])
    homIso .Iso.fun = U/ .F-hom
    homIso .Iso.inv (f , ψ) = f , homoIso .Iso.inv ψ
    homIso .Iso.sec _ = refl
    homIso .Iso.ret _ = refl

    -- THEOREM 1a: the inclusion of the models of the quotient theory
    -- into the models of the original is fully faithful
    isFullyFaithfulU/ : isFullyFaithful (U/ {ℓX = ℓX})
    isFullyFaithfulU/ M N = isoToIsEquiv homIso

    -- THEOREM 1b: it is the full subcategory on the property `Sat E`,
    -- i.e. `MOD (σeq / E)` is *isomorphic* (bijective on objects and
    -- fully faithful) to the total category of the `PropertyOver`
    Q : Functor MOD/ (∫C (SATᴰ ℓX))
    Q .F-ob = obIso .Iso.fun
    Q .F-hom fᴰ = U/ .F-hom fᴰ , tt
    Q .F-id = refl
    Q .F-seq _ _ = refl

    QhomIso : {M N : ob MOD/}
      → Iso (MOD/ [ M , N ]) (∫C (SATᴰ ℓX) [ Q .F-ob M , Q .F-ob N ])
    QhomIso .Iso.fun = Q .F-hom
    QhomIso .Iso.inv (g , _) = homIso .Iso.inv g
    QhomIso .Iso.sec _ = refl
    QhomIso .Iso.ret = homIso .Iso.ret

    isFullyFaithfulQ : isFullyFaithful Q
    isFullyFaithfulQ M N = isoToIsEquiv QhomIso

    isEquivQ-ob : isEquiv (Q .F-ob)
    isEquivQ-ob = isoToIsEquiv obIso

    -- and forgetting the property is the inclusion `U/`
    Q⋆Fst : (Fst ∘F Q) ≡ U/ {ℓX = ℓX}
    Q⋆Fst = Functor≡ (λ _ → refl) (λ _ → refl)

-- Pushing equations forward along a signature map.  This is the
-- "add operations, impose nothing new" half of the factorization: the
-- pushed theory has τ's operations and exactly σeq's equations, read
-- through F.
module _ {σ : AlgTheorySig ℓ1 ℓ'} {τ : AlgTheorySig ℓ2 ℓ'}
  (F : SigMap σ τ) (σeq : AlgTheoryEqns σ ℓ'' ℓv) where

  pushEqns : AlgTheoryEqns τ ℓ'' ℓv
  pushEqns .eqns = σeq .eqns
  pushEqns .vars = σeq .vars
  pushEqns .lhs e = mapTm F (σeq .lhs e)
  pushEqns .rhs e = mapTm F (σeq .rhs e)

  pushPres : PresEqns σeq pushEqns ℓX F
  pushPres X B e ρ =
    TmRec-mapTm F α ρ (σeq .lhs e)
    ∙ Alg.⟦_⟧eqn B e ρ
    ∙ sym (TmRec-mapTm F α ρ (σeq .rhs e))
    where α = Alg.⟨_⟩⟦_⟧op B

  -- a map out of σeq along F is the same as a *vertical* map out of the
  -- pushforward: this is what makes the factorization work
  pullPres : {τeq : AlgTheoryEqns τ ℓE ℓv}
    → PresEqns σeq τeq ℓX F → PresEqns pushEqns τeq ℓX idSigMap
  pullPres pF X B e ρ =
    sym (TmRec-mapTm F α ρ (σeq .lhs e))
    ∙ pF X B e ρ
    ∙ TmRec-mapTm F α ρ (σeq .rhs e)
    where α = Alg.⟨_⟩⟦_⟧op B

-- THEOREM 2: every map of theories factors as (add operations)
-- followed by (add equations).
module _ {σ τ : SetSig ℓ ℓ'} (F : SigMap (σ .sig) (τ .sig))
  {σeq : AlgTheoryEqns (σ .sig) ℓ'' ℓv}
  {τeq : AlgTheoryEqns (τ .sig) ℓ'' ℓv}
  (pF : PresEqns σeq τeq ℓX F) where

  private
    TH = THEORY ℓ ℓ' ℓ'' ℓv ℓX

  midTheory : ob TH
  midTheory = τ , pushEqns F σeq

  addOps : TH [ (σ , σeq) , midTheory ]
  addOps = F , pushPres F σeq

  addEqns : TH [ midTheory , (τ , τeq) ]
  addEqns = idSigMap , pullPres F σeq pF

  factorize : (addOps ⋆⟨ TH ⟩ addEqns) ≡ (F , pF)
  factorize =
    Σ≡Prop (λ f → isPropPresEqns {σeq = σeq} {τeq = τeq} {F = f}) refl

-- A *vertical* map of theories -- one that is the identity on the
-- signature -- says exactly that the target entails the source, i.e.
-- that the target is the source with more equations imposed.  So the
-- quotient construction is the generic vertical map: `σeq / σeq'` is
-- isomorphic to `σeq'` in THEORY.  (Both directions are vertical, and
-- `PresEqns` is a proposition, so the round trips are automatic.)
module _ {σ : SetSig ℓ ℓ'} {σeq σeq' : AlgTheoryEqns (σ .sig) ℓ'' ℓv}
  (p : PresEqns σeq σeq' ℓX idSigMap) where

  private
    TH = THEORY ℓ ℓ' ℓ'' ℓv ℓX

  quotDown : PresEqns (σeq / σeq') σeq' ℓX idSigMap
  quotDown X B (inl e) ρ = p X B e ρ
  quotDown X B (inr e) ρ = Alg.⟦_⟧eqn B e ρ

  quotUp : PresEqns σeq' (σeq / σeq') ℓX idSigMap
  quotUp X B e ρ = Alg.⟦_⟧eqn B (inr e) ρ

  quotCatIso : CatIso TH (σ , σeq / σeq') (σ , σeq')
  quotCatIso .fst = idSigMap , quotDown
  quotCatIso .snd .isIso.inv = idSigMap , quotUp
  quotCatIso .snd .isIso.sec =
    Σ≡Prop (λ f → isPropPresEqns {σeq = σeq'} {τeq = σeq'} {F = f}) refl
  quotCatIso .snd .isIso.ret =
    Σ≡Prop (λ f → isPropPresEqns
      {σeq = σeq / σeq'} {τeq = σeq / σeq'} {F = f}) refl

-- THEOREM 2b: the second factor of `factorize` really is a quotient
-- map, composed with the isomorphism above.
module _ {σ τ : SetSig ℓ ℓ'} (F : SigMap (σ .sig) (τ .sig))
  {σeq : AlgTheoryEqns (σ .sig) ℓ'' ℓv}
  {τeq : AlgTheoryEqns (τ .sig) ℓ'' ℓv}
  (pF : PresEqns σeq τeq ℓX F) where

  private
    TH = THEORY ℓ ℓ' ℓ'' ℓv ℓX
    mid : AlgTheoryEqns (τ .sig) ℓ'' ℓv
    mid = pushEqns F σeq

    pull : PresEqns mid τeq ℓX idSigMap
    pull = pullPres F σeq pF

  quotMap : TH [ (τ , mid) , (τ , mid / τeq) ]
  quotMap = idSigMap , quotPres mid τeq

  addEqnsIsQuot :
    (quotMap ⋆⟨ TH ⟩ (quotCatIso {σ = τ} pull .fst))
      ≡ addEqns {σ = σ} {τ = τ} F pF
  addEqnsIsQuot =
    Σ≡Prop (λ f → isPropPresEqns {σeq = mid} {τeq = τeq} {F = f}) refl

-- THEOREM 2c: the two classes are orthogonal.  Every square from an
-- "add operations" map to a quotient map has a unique diagonal filler,
-- so (add operations, add equations) is an orthogonal factorisation of
-- maps of theories.  Uniqueness is cheap -- `PresEqns` is a
-- proposition, so a map of theories is determined by its signature part
-- -- and the content is that the diagonal's `PresEqns` witness exists.
module _ {σ τ υ : SetSig ℓ ℓ'}
  {σeq : AlgTheoryEqns (σ .sig) ℓ'' ℓv}
  {υeq : AlgTheoryEqns (υ .sig) ℓ'' ℓv}
  (F : SigMap (σ .sig) (τ .sig))
  (E : AlgTheoryEqns (υ .sig) ℓ'' ℓv)
  (ℓX : Level) where

  private
    TH = THEORY ℓ ℓ' ℓ'' ℓv ℓX
    mid : AlgTheoryEqns (τ .sig) ℓ'' ℓv
    mid = pushEqns F σeq

  Lmap : TH [ (σ , σeq) , (τ , mid) ]
  Lmap = F , pushPres F σeq

  Rmap : TH [ (υ , υeq) , (υ , υeq / E) ]
  Rmap = idSigMap , quotPres υeq E

  module _ (u : TH [ (σ , σeq) , (υ , υeq) ])
    (v : TH [ (τ , mid) , (υ , υeq / E) ])
    (sq : (Lmap ⋆⟨ TH ⟩ v) ≡ (u ⋆⟨ TH ⟩ Rmap)) where

    private
      q : (F ⋆SigMap (v .fst)) ≡ u .fst
      q = cong fst sq

      w : PresEqns σeq υeq ℓX (F ⋆SigMap (v .fst))
      w = subst (PresEqns σeq υeq ℓX) (sym q) (u .snd)

      dPres : PresEqns mid υeq ℓX (v .fst)
      dPres X B e ρ =
        sym (TmRec-mapTm F γ ρ (σeq .lhs e))
        ∙ w X B e ρ
        ∙ TmRec-mapTm F γ ρ (σeq .rhs e)
        where γ = reOps (v .fst) (Alg.⟨_⟩⟦_⟧op B)

    diag : TH [ (τ , mid) , (υ , υeq) ]
    diag = v .fst , dPres

    diagUpper : (Lmap ⋆⟨ TH ⟩ diag) ≡ u
    diagUpper =
      Σ≡Prop (λ f → isPropPresEqns {σeq = σeq} {τeq = υeq} {F = f}) q

    diagLower : (diag ⋆⟨ TH ⟩ Rmap) ≡ v
    diagLower = Σ≡Prop
      (λ f → isPropPresEqns {σeq = mid} {τeq = υeq / E} {F = f}) refl

    orthogonal : isContr (Σ[ d ∈ TH [ (τ , mid) , (υ , υeq) ] ]
      (((Lmap ⋆⟨ TH ⟩ d) ≡ u) × ((d ⋆⟨ TH ⟩ Rmap) ≡ v)))
    orthogonal .fst = diag , diagUpper , diagLower
    orthogonal .snd (d , h1 , h2) = Σ≡Prop
      (λ _ → isProp× (TH .Category.isSetHom _ _)
                     (TH .Category.isSetHom _ _))
      (Σ≡Prop (λ f → isPropPresEqns {σeq = mid} {τeq = υeq} {F = f})
        (sym (cong fst h2)))

-- THEOREM 3: the inclusion is reflective.  The reflection of a model
-- `B` of `σeq` is `B` presented by its own multiplication table over
-- the quotient theory: generators the carrier of `B`, one relation
-- `op(x) = ⟨op⟩⟦x⟧` for every operation and every tuple of elements.
-- Because a relation is an equation with no variables, imposing the
-- table forces nothing beyond `B`'s own structure, and `E` is imposed
-- by the base theory -- so the presented model *is* `B` modulo the
-- congruence generated by `E`, with no new quotient HIT.
--
-- This is the only place where arities and equation variables must
-- live at the same level: `Presentation` is stated for
-- `AlgTheorySig ℓ ℓv`, and the generators are the carrier of `B`.
module _ {σ : AlgTheorySig ℓ ℓv} (σeq : AlgTheoryEqns σ ℓ'' ℓv)
  (E : AlgTheoryEqns σ ℓE ℓv) {V : Type ℓv} (B : Alg σeq V) where

  private
    σ/E : AlgTheoryEqns σ (ℓ-max ℓ'' ℓE) ℓv
    σ/E = σeq / E

  tableP : Presentation σ V (ℓ-max ℓ ℓv)
  tableP .rels = Σ[ op ∈ σ .ops ] (σ .arities op → V)
  tableP .rl (op , x) = node op (λ a → var (x a))
  tableP .rr (op , x) = var (Alg.⟨_⟩⟦_⟧op B op x)

  Reflect : Type (ℓPres tableP σ/E)
  Reflect = Presented tableP σ/E

  ReflectAlg : Alg σ/E Reflect
  ReflectAlg = PresentedσAlg tableP σ/E

  module _ {X : Type ℓX} (isSetX : isSet X) (A : Alg σ/E X) where

    private
      Aσ : Alg σeq X
      Aσ = Alg∪ σeq E A

      relOf : (ρ : V → X) → Type (ℓ-max (ℓ-max ℓ ℓv) ℓX)
      relOf ρ = (e : tableP .rels)
        → TmRec (Alg.⟨_⟩⟦_⟧op A) ρ (tableP .rl e)
          ≡ TmRec (Alg.⟨_⟩⟦_⟧op A) ρ (tableP .rr e)

      opHomB : {ρ : V → X} → Homo σeq ρ B Aσ
        → (op : σ .ops) (x : σ .arities op → V) (y : V)
        → y ≡ Alg.⟨_⟩⟦_⟧op B op x
        → ρ y ≡ Alg.⟨_⟩⟦_⟧op Aσ op (ρ ∘ x)
      opHomB ψ = Homo.op-hom ψ

      toHomo : {ρ : V → X} → relOf ρ → Homo σeq ρ B Aσ
      toHomo {ρ} rel .Homo.op-hom op x y eq =
        cong ρ eq ∙ sym (rel (op , x))

      fromHomo : {ρ : V → X} → Homo σeq ρ B Aσ → relOf ρ
      fromHomo ψ (op , x) = sym (opHomB ψ op x _ refl)

    -- the underlying data of a map out of the reflection
    Reflected : Type (ℓ-max (ℓ-max ℓ ℓv) ℓX)
    Reflected = Σ[ ρ ∈ (V → X) ] Homo σeq ρ B Aσ

    pointsIso : Iso (Points tableP σ/E isSetX A) Reflected
    pointsIso .Iso.fun (ρ , rel) = ρ , toHomo rel
    pointsIso .Iso.inv (ρ , ψ) = ρ , fromHomo ψ
    pointsIso .Iso.sec (ρ , ψ) =
      Σ≡Prop (λ _ → isPropHomo σeq isSetX) refl
    pointsIso .Iso.ret (ρ , rel) =
      Σ≡Prop (λ _ → isPropΠ λ _ → isSetX _ _) refl

    -- THE REFLECTION: homomorphisms of `σeq / E`-models out of the
    -- reflection are homomorphisms of `σeq`-models out of `B`
    UPReflect : Iso (σHom tableP σ/E isSetX A) Reflected
    UPReflect = compIso (UPPresented tableP σ/E isSetX A) pointsIso

  -- packaged in MOD: `ReflectOb` is the reflection of `(V , B)` and
  -- `UPReflectMOD` is the adjunction isomorphism
  private
    ℓR : Level
    ℓR = ℓPres tableP σ/E

    MOD/E = MOD σ/E ℓR

  ReflectOb : ob MOD/E
  ReflectOb = PresentedOb tableP σ/E .fst , ReflectAlg

  UPReflectMOD : (N : ob MOD/E)
    → Iso (MOD/E [ ReflectOb , N ]) (Reflected (N .fst .snd) (N .snd))
  UPReflectMOD N = UPReflect (N .fst .snd) (N .snd)

  -- the unit: the generators, as a homomorphism of `σeq`-models
  unitReflect : Reflected (ReflectOb .fst .snd) ReflectAlg
  unitReflect =
    UPReflectMOD ReflectOb .Iso.fun (MOD/E .Category.id)

  -- the isomorphism is restriction along the unit ...
  UPReflectβ : (N : ob MOD/E) (h : MOD/E [ ReflectOb , N ])
    → UPReflectMOD N .Iso.fun h .fst ≡ (h .fst) ∘ (unitReflect .fst)
  UPReflectβ N h = refl

  -- ... hence natural in N
  UPReflectNat : (N N' : ob MOD/E)
    (h : MOD/E [ ReflectOb , N ]) (k : MOD/E [ N , N' ])
    → UPReflectMOD N' .Iso.fun (h ⋆⟨ MOD/E ⟩ k)
      ≡ ( (k .fst) ∘ (UPReflectMOD N .Iso.fun h .fst)
        , (_⋆Homo_ σeq (UPReflectMOD N .Iso.fun h .snd)
            (homoIso σeq E .Iso.fun (k .snd))) )
  UPReflectNat N N' h k =
    Σ≡Prop (λ _ → isPropHomo σeq (N' .fst .snd)) refl
