{-

  The free model of `MagmaSketch`, as a check that the general
  construction of `Cubical.Algebra.Sketch.Free.Base` instantiates at a
  sketch that is not merely formal.

  `MagmaSketch` has one designated cone, of discrete shape `Bool`,
  exhibiting `⟨X²⟩` as a binary product.  Its free model on generators
  `G` at the sort `⟨X⟩` therefore has

    * `FM ⟨X²⟩ ≅ FM ⟨X⟩ × FM ⟨X⟩`, which is `medIso` after discharging
      the (contractible) compatibility condition of a discrete shape,
    * a binary operation `_·_` on `FM ⟨X⟩`, obtained by pairing and
      then applying the index morphism `op`.

  So the free magma is recovered, in the sense of the sketch: the
  carrier `FM ⟨X⟩` is a magma freely generated by `G`, the freeness
  being `UPModel`.

-}
module Cubical.Algebra.Sketch.Free.Magma where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Isomorphism

open import Cubical.Data.Bool
open import Cubical.Data.Empty using (⊥ ; ⊥*)
open import Cubical.Data.Sigma
open import Cubical.Data.Unit

open import Cubical.Categories.Category
open import Cubical.Categories.Functor
open import Cubical.Categories.Instances.Sets

open import Cubical.Algebra.Sketch.Base
open import Cubical.Algebra.Sketch.Instances.Magma
open import Cubical.Algebra.Sketch.Free.Base

private
  variable
    ℓ : Level

open Category
open Functor

module _ (G : Type ℓ) where

  -- generators at the sort only
  Gn : MagmaOb → Type ℓ
  Gn ⟨X⟩ = G
  Gn ⟨X²⟩ = ⊥*

  FM : MagmaOb → Type ℓ
  FM = Free MagmaSketch Gn

  noCocones : Sketch.CIdx MagmaSketch → ⊥
  noCocones ()

  FreeMagmaModel : Model MagmaSketch (SET ℓ)
  FreeMagmaModel = FreeModel MagmaSketch Gn noCocones

  -- A discrete shape imposes no compatibility condition: every hom of
  -- `MagmaInd` out of `⟨X⟩` is `tt`, so the action of the diagram on a
  -- shape morphism is the action of the identity.
  tupleCompat : (t : Bool → FM ⟨X⟩) → Compat MagmaSketch Gn tt t
  tupleCompat t {j} e = actId (t j) ∙ cong t e

  bothOf : FM ⟨X⟩ → FM ⟨X⟩ → Bool → FM ⟨X⟩
  bothOf a b false = a
  bothOf a b true = b

  tuple : FM ⟨X⟩ → FM ⟨X⟩ → FM ⟨X²⟩
  tuple a b = med tt (bothOf a b) (tupleCompat (bothOf a b))

  proj₁β : (a b : FM ⟨X⟩) → act p₁ (tuple a b) ≡ a
  proj₁β a b = medβ tt (bothOf a b) (tupleCompat (bothOf a b)) false

  proj₂β : (a b : FM ⟨X⟩) → act p₂ (tuple a b) ≡ b
  proj₂β a b = medβ tt (bothOf a b) (tupleCompat (bothOf a b)) true

  tupleIso : Iso (FM ⟨X²⟩) (FM ⟨X⟩ × FM ⟨X⟩)
  tupleIso .Iso.fun u = act p₁ u , act p₂ u
  tupleIso .Iso.inv (a , b) = tuple a b
  tupleIso .Iso.sec (a , b) = ΣPathP (proj₁β a b , proj₂β a b)
  tupleIso .Iso.ret u =
    medPath MagmaSketch Gn tt
      (λ { false → refl ; true → refl })
      (tupleCompat (bothOf (act p₁ u) (act p₂ u)))
      (projCompat MagmaSketch Gn tt u)
    ∙ medηPath MagmaSketch Gn tt u

  -- the free magma structure
  _·_ : FM ⟨X⟩ → FM ⟨X⟩ → FM ⟨X⟩
  a · b = act op (tuple a b)

  var : G → FM ⟨X⟩
  var = gen
