name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.org'
      - 'Notes/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.org'
      - 'Notes/*'
  workflow_dispatch:

# Dependencies pinned in flake.lock
# Bump with `nix flake update` locally and commit the lock;
# or edit the lock file directly
#
# Dependencies saved in nix store and cached
#
# cubical-categorical-logic builds are cached and need only
# rebuild changed files
#
# Can check well-formedness of this workflow locally with act or actionlint
#   nix run nixpkgs#actionlint
#   nix run nixpkgs#act -- -j build --dryrun
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          skip-restore-on-hit-primary-key: false

      - name: Cache library _build
        uses: actions/cache@v5
        with:
          path: ./_build
          key: ccl-build-${{ runner.os }}-${{ hashFiles('flake.lock') }}-${{ hashFiles('Cubical/**', 'Gluing/**', 'Syntax/**', 'Multicategory/**', 'Guarded/**', 'cubical-categorical-logic.agda-lib') }}
          restore-keys: |
            ccl-build-${{ runner.os }}-${{ hashFiles('flake.lock') }}-
            ccl-build-${{ runner.os }}-

      - name: Check whitespace
        run: nix develop --command fix-whitespace --check

      - name: Typecheck library
        run: nix develop --command make check

      - name: Htmlize
        if: (github.event_name == 'push' && github.ref_name == 'main') || github.event_name == 'workflow_dispatch'
        run: nix develop --command make listings

      - name: Deploy to GitHub Pages
        if: (github.event_name == 'push' && github.ref_name == 'main') || github.event_name == 'workflow_dispatch'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: html
